services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sua_marca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  registry:
    image: verdaccio/verdaccio:5
    ports:
      - "4873:4873"
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_conf:/verdaccio/conf
volumes:
  postgres_data:
  verdaccio_storage:
  verdaccio_conf:
