storage: /verdaccio/storage
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
packages:
  '@sua-marca-pro/*':
    access: $all
    publish: $authenticated
  '@sua-marca/*':
    access: $all
    publish: $authenticated
logs:
  - {type: stdout, format: pretty, level: http}
